### ISSUE TITLE
Facing some problems in evaluation

### ISSUE THREAD

**Issue by PRSJMC** [Kikyo-16/A-unified-model-for-zero-shot-musical-source-separation-transcription-and-synthesis#3]
When I tried to make evaluation, it reports an error as below.
 

> File "evaluate.py", line 39, in <module> preds = inference.inference()
File "/root/autodl-tmp/1/src/inference/inference.py", line 200, in inference for sample in self.test_data.test_samples():
File "/root/autodl-tmp/1/src/dataset/urmp/urmp_test.py", line 89, in test_samples with h5py.File(ref, 'r') as hf:
  File "/root/miniconda3/lib/python3.8/site-packages/h5py/_hl/files.py", line 424, in __init__
    fid = make_fid(name, mode, userblock_size,
File "/root/miniconda3/lib/python3.8/site-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'dataset/hdf5s/urmp/38_Jerusalem_vn_vn_va_vc_db/AuSep_4_vc_38_Jerusalem.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

  
It seems the dataset only includes 'AuSep_4_vc_38_Jerusalem._TEST.h5' as below.
![image](https://user-images.githubusercontent.com/46528990/147932591-e13ef01b-38fc-4630-9cc9-8d72892233f7.png)

**Comment by PRSJMC** [comment]
By the way, it takes 'a extremely long time' to evaluate a model in one epoch.
With the GPU 0%,CPU 100%, if I use Test.h5 as the h5 file the evaluate.py needs.

**Comment by PRSJMC** [comment]
After evaluating all last-10-epoch models, I get the result table as below.
![image](https://user-images.githubusercontent.com/46528990/148000401-c4bcf88c-e80b-44d6-9211-2c2ddc2c9301.png)

Due to pytorch support problems, my training environment is different from the requirement list in the following aspects.
> RTX3090 torchvision==0.8.2+cu110 torchaudio===0.7.2 torchlibrosa==0.0.4 torch==1.7.1+cu110

**Comment by Kikyo-16** [comment]
Hi,  I have fixed the bug you mentioned and enabled a multiple-process setting of evaluation. Hence, the evaluation takes less time now. I also upload the model weights and evaluation results. If you follow the experimental settings we provide, you can reproduce the same results as we do in our paper. But if you do not keep the same experimental environment, due to different computational accuracies of different PyTorch versions, it is possible that you get slightly different results.
