### ISSUE TITLE
REQUEST A CHECKPOINT MODEL

### ISSUE THREAD

**Issue by playdasegunda** [Kikyo-16/A-unified-model-for-zero-shot-musical-source-separation-transcription-and-synthesis#4]
Hi, do you offer any checkpoint model? to test the results on our own sounds? Thank you very much.

**Comment by Kikyo-16** [comment]
Hi, you can find model weights [here](https://drive.google.com/drive/folders/1fT3Fva5JywhpYnOhsORbDkLQ9Vnhv_Lj?usp=sharing).
